apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: hello 
    ver: "1.0"

spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
