apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-deployment
  namespace: default
spec:
  ports:
  - nodePort: 32306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: NodePort
